import type { Metadata } from "next";

import "./globals.css";
import { font } from '@/app/ui/fonts'  // Adjusted import to match the correct export


export const metadata: Metadata = {
  title: "Ask Aussie",
  description: "Generated by Arc AI Agent",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>

      <body className={`${font.className} antialiased`}>{children}</body>
    </html>
  );
}
