import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Saira_Condensed } from "next/font/google";
import "./globals.css";
import { SourceCodePro } from '@/app/ui/fonts'  // Adjusted import to match the correct export

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sairaCondensed = Saira_Condensed({
  variable: "--font-saira-condensed",
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
       
      </head>

      <body className={`${SourceCodePro.className} antialiased`}>{children}</body>
    </html>
  );
}
